edition = "2024"
style_edition = "2024"
match_block_trailing_comma = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
max_width = 120
comment_width = 120
chain_width = 60
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true